version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: "webkelas_db_skripsi"
      MYSQL_USER: "webkelas_aping"
      MYSQL_PASSWORD: "Vp5KEaWY^Iq)"
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  pma:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=toor
volumes:
  my-db:
